name: custard-ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/custard/test/**
  pull_request:
    paths-ignore:
      - .github/custard/test/**
  workflow_dispatch:

jobs:

  # Find the packages that were changed
  affected:
    uses: glasnt/trifle/.github/workflows/affected.yaml@debugging-matchPackages
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.workflow_run.head_sha || github.sha }}
      config-file: .github/config.jsonc

  # Run linting against changed packages (command is run in cwd of affected path)
  lint:
    needs: affected
    uses: ./.github/workflows/lint.yaml
    with:
        paths: ${{ needs.affected.outputs.paths }}

  debugging:
    needs: affected
    runs-on: ubuntu-latest
    steps:
      - uses: glasnt/trifle/actions/steps/map-run@debugging-matchPackages
        with:
          command: echo hi
          paths: ${{ needs.affected.outputs.paths }}
      - uses: glasnt/trifle/actions/steps/map-run@debugging-matchPackages
        with:
          command: python --version
          paths: ${{ needs.affected.outputs.paths }}
      - uses: glasnt/trifle/actions/steps/map-run@debugging-matchPackages
        with:
          command: npm --version
          paths: ${{ needs.affected.outputs.paths }}



  # Run tests against changed packages
  test:
    needs: affected
    runs-on: ubuntu-latest
    steps:
      - uses: glasnt/trifle/actions/steps/map-run@debugging-matchPackages
        with:
          command: pip install -r requirements-test.txt && pytest
          paths: ${{ needs.affected.outputs.paths }}

  # Confirm all checks complete
  done:
    needs: [affected, test, lint]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: glasnt/trifle/actions/steps/update-check@v0.0.10
        with:
          check: ${{ needs.affected.outputs.check }}
          status: success
