
name: lint
on:
  workflow_call:
    inputs:
      paths:
        description: A JSON list of package paths.
        required: true
        type: string

jobs:

  lint:
    if: inputs.paths != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head-sha }}
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14 # ${{ inputs.python-version }}
      - name: Install Dependencies
        run: |
          pip install black
          echo "Contents of paths-json: ${{ inputs.paths-json }}"
      - name: Run Lint
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/map-run@main
        with:
          command: black *.py
          paths: ${{ inputs.paths }}
          outputs-always: true
